- index.html
- package-lock.json
- package.json
- src/assets/column.css
- src/components/ProductItem.vue
- src/stores/products
- src/views/HomeView.vue
- src/views/ProductList.vue
- ProductItem 元件
- Element plus package -> 下拉選單
-  vue-awesome-paginate  package-> 分頁
- ProductItem 元件
-  vue-awesome-paginate  package-> 分頁
> feat: productList、co-branding section

- src/components/googleLogin.vue
- 在 register 的 alert 上新增顯示使用者的信箱提升體驗
- 修改 sweetalert2 按鈕樣式符合主題色
- 移除 google login 功能的 所有 console.log()
> 修改 Register alert、移除 console.log

- src/components/Footer.vue
- src/components/ProductItem.vue
- src/router/index.js
- src/views/ProductList.vue
- 移除加入購物車要驗證登入
- 移除進入 cart 頁面要驗證登入
- 先把 footer 裡沒用到的 link 改成 #，不會出 warning
> 移除加入購物車要驗證登入

- package-lock.json
- package.json
- src/App.vue
- src/components/AddSharedCart.vue
- src/components/NavBar.vue
- src/components/ProductItem.vue
- src/components/SharedCartItem.vue
- src/router/index.js
- src/stores/cart.js
- src/stores/sharedCart.js
- src/views/Cart.vue
- src/views/ProductList.vue
- src/views/RegisterLogin.vue
- src/views/SharedCartList.vue
- 共享購物車列表，含 RWD
- 新增共享購物車彈窗
- 創建共享購物車
- 共享購物車共用 購物車 頁面(依據路徑判斷)
- 新增購物車是空的的畫面
> 共享購物車列表、創建

- src/App.vue
- src/components/ProductItem.vue
> feat:add to top button and change icon color

- src/App.vue
> 改 icon 顏色為黑色

- README.md
> README.md 草稿

- src/components/NavBar.vue
- src/router/index.js
- src/views/SearchResult.vue
> Added:搜尋功能

- src/views/SearchResult.vue
加入購物車按鈕的
lg:-top-50px
改
lg:top-[-50px]
> fix:#53 修正搜尋結果商品圖跑版

- src/views/SearchResult.vue
- 原用複製 ProductItem.vue 的方式，經建議修改成使用 ProductItem.vue 跑 v-for
> fix:更改使用productItem 跑 v-for

- src/views/Cart.vue
> fix: #81 購物車相關 API 都要在 headers 帶 userId

- src/components/Warning.vue
- src/stores/cart.js
- src/stores/sharedCart.js
- src/views/Cart.vue
- src/views/ProductDetail.vue
Reverts 33test/clone-bonny#87
因為新增了 "加入商品到共享購物車" 功能，希望重新 PR
> Revert "style: 修改警告彈窗的 max-width"

- Caddyfile
- index.html
- nixpacks.toml
- src/views/HomeView.vue
- vite.config.js
> deploy: 同步部署設定到 dev

- src/App.vue
- src/components/CartProduct.vue
- src/views/Cart.vue
- src/views/backupCart.vue
> 修改購物車功能頁面樣式

- .env.example
- package-lock.json
- package.json
- src/components/AddSharedCart.vue
- src/components/CartProduct.vue
- src/stores/sharedCart.js
- src/views/Cart.vue
- src/views/ProductDetail.vue
- src/websocket/websocket.js
- 共享購物車的好友編輯數量會即時更新
- 共享購物車的好友刪除商品會即時更新
- 共享購物車的好友新增商品會即時更新
- 以上三個行為都會飄過彈幕（在共享購物車頁面）
> feat: #78 WebSocket 處理共享購物車的共編

- src/stores/sharedCart.js
- src/views/Cart.vue
- src/views/HomeView.vue
- src/views/ProductDetail.vue
> feat: #103 共享購物車發 Email

- package.json
- src/App.vue
- src/router/index.js
- src/stores/cart.js
- src/views/Cart.vue
- src/views/Debit.vue
結帳頁面還沒有抓 deliver 表的手機（等 API 上了我再抓）
> feat: #122 結帳頁面可以正常吃到數據、進綠界

- src/views/Debit.vue
- src/views/MemberWishList.vue
> feat: #132 追蹤清單加入購物車、加入共享購物車串接

- src/components/Logout.vue
- src/components/NavBar.vue
- src/views/ProductDetail.vue
- src/views/RegisterLogin.vue
- #89 
- 註冊登入彈窗完善
- sidebar類別點擊後自動收回
- 商品詳情後端 API 調整為 SRP 原則修繕
- 登出提示確認彈窗
> feat : #89 新增註冊生日輸入功能

- src/components/googleLogin.vue
- src/views/ProductDetail.vue
> style: GoogleLogin 頁面 alert 樣式改 ElMessage、共享購物車要先登入，跳警告

- src/views/Cart.vue
- src/views/MemberCoupons.vue
> Added:會員頁面優惠券跟購物車優惠券扣除

- package-lock.json
- src/components/ProductItem.vue
- src/main.js
- src/stores/cart.js
- src/views/Cart.vue
- src/views/ProductDetail.vue
- 未登入的使用者把商品加入購物車會存在 LocalStorage
- 登入之後進入購物車會把 LocalStorage 的東西存到使用者的購物車（沒有一登入就打 API 會有些缺點，比如進入購物車之前的數據是錯的，購物車頁面的渲染可能會有點久）
> feat: #110 未登入的時候加入購物車功能

- src/views/Debit.vue
- src/views/MemberWishList.vue
結帳頁面輸入格式檢查
- 手機
- 地址
- 區域
修正願望清單 undefined 的問題
- 多傳商品名稱
> 結帳頁面輸入格式檢查、修正願望清單 undefined 的問題

- src/views/OrderDetails.vue
- src/views/product_review_comments.vue
> fix : #153 驗證使用者UID是不是訂單主人

- src/components/Reviews.vue
- src/views/MemberOrder.vue
- src/views/MemberWishList.vue
- src/views/ProductDetail.vue
星星套件樣式修正
會員訂單頁新增一個try catch去抓有問題的訂單
再把其他訂單渲染出來
調整追蹤清單樣式
> Issue#161 修改樣式及訂單頁BUG

- src/views/Cart.vue
- src/views/ProductDetail.vue
- src/views/ProductList.vue
- src/views/SearchResult.vue
> feat: 產品詳情、產品列表、搜尋結果 加上 loading 畫面

- src/components/NavBar.vue
>  adjust : logo border 調整

- src/components/NavBar.vue
- src/views/MemberOrder.vue
- src/views/MemberWishList.vue
- src/views/ProductDetail.vue
feat : #148 會員介面、商品詳情、幣種切換成功通知
> adjust : UI調整
